# fly.toml app configuration file generated for pixelz3d on 2023-10-12T15:11:06-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pixelz3d"
primary_region = "mia"

[build]

[env]
  PORT = "8080"

[http_service]
  internal_port = 3000
  force_https = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
